services:
  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000'
      - '4317'
      - '4318'
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=${DB_NAME:-expense-app}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD:-secret}'
      - 'POSTGRES_USER=${DB_USERNAME:-mateo-local}'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
  keycloak:
    image: 'quay.io/keycloak/keycloak:26.7.4'
    command: 'start-dev --import-realm'
    environment:
      - 'KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN:-admin}'
      - 'KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}'
      - 'GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}'
      - 'GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}'
    ports:
      - '8081:8080'
    volumes:
      - 'keycloak-data:/opt/keycloak/data'
      - './keycloak:/opt/keycloak/data/import'

volumes:
  postgres-data:
  keycloak-data:
